import {Home} from './Home/Home';
import {Playlist} from './Playlist/Playlist';
import { LikedVideos } from './LikedVideos/LikedVideos';
import { WatchLater } from './WatchLater/Watchlater';
import { History } from './History/History';
import {Login} from './Auth/Login/Login';
import {SignUp} from './Auth/SignUp/SignUp';
import {Profile} from './Profile/Profile';
import { SingleVideo } from './SingleVideo/SingleVideo';
export {Home,Playlist,LikedVideos,WatchLater,History,Login,SignUp,Profile,SingleVideo};
