const VIDEOLISTING_ACTIONS={
    INITIAL_VIDEOS:"INITIAL_VIDEOS",
    CATEGORIES:"CATEGORIES",
    FILTER_BY_CATEGORY:"FILTER_BY_CATEGORY",
    
}
const SINGLE_VIDEO_ACTIONS={
    LIKE_VIDEO:"LIKE_VIDEO",
    REMOVE_LIKED_VIDEO:"UPDATE_LIKED_VIDEO",
}
export {VIDEOLISTING_ACTIONS,SINGLE_VIDEO_ACTIONS};